# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BryanPH
url: https://bryanph.com  # the base hostname & protocol for your site
repository: https://github.com/bryandph/bryanph-site
description: Built with <a href="https://jekyllrb.com/">Jekyll</a> utilizing <a href="http://hackcss.com/">hackcss</a>!

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard # choices are: 'dark', 'standard', 'markdown', 'dark-grey', 'solarized-dark'

# Customizations
your_name: Bryan Prather-Huff
email: bryan@pratherhuff.com

navigation:
  - text: Home
    url: /
  - text: Blog
    url: /blog
  - text: Resume
    url: /resume

projects:
  - name: git-secret
    description: A bash-tool to store your private data inside a git repository.
    link: https://sobolevn.github.io/git-secret
    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true

social:
  - service: github
    username: GitHub
    link: https://github.com/bryandph
  # - service: facebook
  #   username: Facebook
  #   link: https://www.facebook.com/Bryan.Prather.Huff
  - service: linkedin
    username: Linkedin
    link: https://www.linkedin.com/in/bryan-prather-huff-368116102
  - service: spotify
    username: Spotify
    link: https://open.spotify.com/user/1218050924

# Plugins
gems:
  - jekyll-seo-tag
